### ISSUE TITLE
PEAR package PHP_Archive not installed Warning Causing Install Abort

### ISSUE THREAD

**Issue by cgunnels** [php-build/php-build#115]
I keep getting this error trying to install various version of php. What can I do to fix this?PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.

**Comment by yupmin** [comment]
i found this fix. 
autoconf is needed. at ubuntu 12.04 
```bash
sudo apt-get install autoconf
```
'> \dev\null' it is the cause for this issue.

**Comment by sumityadav** [comment]
On OSX while installing 7.0.0 i get the same error:

```
Generating phar.php
Generating phar.phar
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.
clicommand.inc
directorygraphiterator.inc
directorytreeiterator.inc
invertedregexiterator.inc
pharcommand.inc
phar.inc
```

**Comment by GrahamCampbell** [comment]
Pear support has been dropped now.

**Comment by spolischook** [comment]
@yupmin thanks, it's works!

**Comment by jmfarina** [comment]
Hello, sorry to re-open this, but I'm experiencing this problem with the latest version.
I get several different warnings while trying to install (in my case, php version 5.6.30), ending with a
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.

I followed @iamfinky 's suggestion and it worked like a charm (just had to run phpenv rehash afterwards to have the shell find the php command).
I'm not familiar with the code for the installation process, but given the error and the workaround, I would guess there's another problem, maybe some error that's not making it to the log ( @yupmin mentions a '> \dev\null', though for me it worked without installing autoconf as he proposes).

**Comment by mxdlx** [comment]
My 2 cents on this. I also got compilation aborted but this thread saved me. Some data:
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux grav 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
```
Also wrote down every package installed to get this working so I hope this helps:
```
build-essential
re2c
libxml2-dev
bison (asks for <2.7 version but apt-get got 3.0)
pkg-config
libbz2-dev
libcurl4-gnutls-dev
libjpeg-dev
libpng12-dev
libmcrypt-dev
libtidy-dev
libxslt1-dev
autoconf 
```

**Comment by 412445773** [comment]
> 
> 
> Problem lies here https://github.com/php/php-src/blob/5.4/ext/phar/phar/pharcommand.inc#L256

links 404

**Comment by 412445773** [comment]
It occers when I compiling php-7.3.2 on CentOS7.
Here is my solution :
1. Ignore the message;
2. Complete the `make install` step;
3. `pear channel-update pear.php.net`
4. `pear install channel://pear.php.net/PHP_Archive-0.12.0`

**Comment by pfirtelu** [comment]
I also have this problem on various versions of php (eg. 7.3.7, 5.x):
`.lo Zend/zend_objects.lo Zend/zend_object_handlers.lo Zend/zend_objects_API.lo Zend/zend_default_classes.lo Zend/zend_inheritance.lo Zend/zend_smart_str.lo Zend/zend_cpuinfo.lo Zend/zend_execute.lo main/internal_functions_cli.lo main/fastcgi.lo sapi/cgi/cgi_main.lo -lcrypt -lcrypto -lssl -lcrypto -lcrypt -lrt -lpng -lz -ljpeg -lz -lcrypto -lssl -lcrypto -lrt -lm -ldl -lnsl -lxml2 -lcurl -lxml2 -lfreetype -lz -lxml2 -lxml2 -lcrypt -lxml2 -lxml2 -lxml2 -lcrypt  -o sapi/cgi/php-cgi
Generating phar.php
Generating phar.phar
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.
make: *** [ext/phar/phar.phar] Ungültiger Maschinenbefehl`

Unfortunately all your posted links are dead. Whats the main cause for this?

**Comment by bryanbreener** [comment]
intenta con sudo 
sudo make install

**Comment by SyntaxError843** [comment]
> My 2 cents on this. I also got compilation aborted but this thread saved me. Some data:
> 
> ```
> $ cat /etc/os-release
> PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
> NAME="Debian GNU/Linux"
> VERSION_ID="8"
> VERSION="8 (jessie)"
> ID=debian
> HOME_URL="http://www.debian.org/"
> SUPPORT_URL="http://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> 
> $ uname -a
> Linux grav 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
> ```
> 
> Also wrote down every package installed to get this working so I hope this helps:
> 
> ```
> build-essential
> re2c
> libxml2-dev
> bison (asks for <2.7 version but apt-get got 3.0)
> pkg-config
> libbz2-dev
> libcurl4-gnutls-dev
> libjpeg-dev
> libpng12-dev
> libmcrypt-dev
> libtidy-dev
> libxslt1-dev
> autoconf 
> ```

fucking hero right here, NONE of these packages were mentioned ANYWHERE!

**Comment by adamthomason** [comment]
For anybody hitting this issue on Ubuntu 20.04 with PHP 8.x, the above comment on packages not mentioned was priceless. I had to use libpng-dev instead of libpng12-dev, but after running the following, everything worked:

```
sudo apt update && sudo apt install build-essential re2c libxml2-dev bison pkg-config libbz2-dev libcurl4-gnutls-dev libjpeg-dev libpng-dev libmcrypt-dev libtidy-dev libxslt1-dev autoconf
```

**Comment by aledebarba** [comment]
Well, my compilation failed at this point too and it happens that I can't use sudo on this server. The solution for me was ask PEAR to install the missing package and things worked out.

Hope it helps:

pear install PHP_Archive-0.14.0

[Here is the PEAR page with more information](https://pear.php.net/package/PHP_Archive/download/All)

**Comment by crdev13** [comment]
> For anybody hitting this issue on Ubuntu 20.04 with PHP 8.x, the above comment on packages not mentioned was priceless. I had to use libpng-dev instead of libpng12-dev, but after running the following, everything worked:
> 
> ```
> sudo apt update && sudo apt install build-essential re2c libxml2-dev bison pkg-config libbz2-dev libcurl4-gnutls-dev libjpeg-dev libpng-dev libmcrypt-dev libtidy-dev libxslt1-dev autoconf
> ```

Thanks, it works
