### ISSUE TITLE
Delete the destination folder on failed install

### ISSUE THREAD

**Issue by Kostanos** [php-build/php-build#125]
I just run the script with wrongly set path to $HOME (stupid), but imaging what this script did:

    function cleanup_abort {
        log "Warn" "Aborting build."

        rm -rf "$PREFIX"

        make -C "$TMP/source/$DEFINITION" clean &> /dev/null
    }

Just deleted all my HOME without any alert.

What I consider the bug here, that cleanup_abort, should only delete files it created!

**Comment by abackstrom** [comment]
This just bit me and deleted my whole `/usr/local` directory.

**Comment by GrahamCampbell** [comment]
Sounds dangerous. Might be useful to leave it there for people to try to debug anyway.

**Comment by gerardroche** [comment]
@GrahamCampbell Just beat me to it. Yes, this is very dangerous.

**Comment by gerardroche** [comment]
@GrahamCampbell did you mean to close this issue?

**Comment by GrahamCampbell** [comment]
Yes, I did. I can of re-open it if anyone from the core team objects though.

**Comment by GrahamCampbell** [comment]
Oh, wait. I misread this. I think we should change the behaviour not to delete stuff...

**Comment by GrahamCampbell** [comment]
Does #277 do the job?

**Comment by GrahamCampbell** [comment]
Thanks for catching @gerardroche. :)

**Comment by gerardroche** [comment]
@GrahamCampbell Personally I'd prefer the requirement that `$PREFIX` not exist at all before creating it. Then the prefix dir can be removed safely because it was newly created by php-build. It also prevents from installing in a directory that already has files resulting in a mess of existing files and the php build files.

**Comment by GrahamCampbell** [comment]
Could you send a pull please?

**Comment by gerardroche** [comment]
@GrahamCampbell Actually thinking about I don't really see the need to be deleting the prefix at all. I would still like to require that the prefix does not exist to begin with.

**Comment by CHH** [comment]
@gerardroche sounds like a good idea. Thanks for the great work!

**Comment by gerardroche** [comment]
@GrahamCampbell Sorry I hadn't forgotten about it. Removing the deletiion is good for now.

**Comment by GrahamCampbell** [comment]
> Removing the deletiion is good for now.

Yeh, that was the idea. I just wanted to get this fixed asap.

If you want to send an additional PR at some point, feel free. :)
