### ISSUE TITLE
Add support for PHP 5.3.3-rhel

### ISSUE THREAD

**Issue by andrerom** [php-build/php-build#140]
It's nice that 5.3.3 is provided for all us that need it for our supported platforms. But unfortunately lots of bugs have been fixed since the release of 5.3.3, quite some [segmentation](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/10199518) [fault](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/10238524) [bugs](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/7658270), some of which have been fixed in the RedHat/CentOs packages.

Therefor it would be better to modify the 5.3.3 version with all [the relevant] RedHat/CentOs patches applied, as it would represent the more stable, more secure version of PHP 5.3.3 that actual users use in the wild.

~~A search for "php-5.3.3-23" will provide lots of links to rpm packages for 5.3.3 for CentOs and RedHat, is available on [CentOs mirror](http://mirror.centos.org/centos/6/os/x86_64/Packages/).~~
Packages can be found on [rpmfinder.net](http://rpmfind.net/linux/RPM/centos/updates/6.6/i386/Packages), latests php package as of writing 5.3.3-40.el6_6: http://rpmfind.net/linux/RPM/centos/updates/6.6/i386/Packages/php-5.3.3-40.el6_6.i686.html

**Comment by GrahamCampbell** [comment]
Given that php 5.3 is EOL and php 5.4 will be soon, we shouldn't be encouraging the use of php 5.3.3.

**Comment by andrerom** [comment]
This issue is unfortunately still relevant as distros maintain their own patched version of PHP for long time.

The suggestion to apply RHEL/Centos patches on 5.3.3 (selectively) will also probably help solve the openssl issue causing problems for composer now. ref: https://twitter.com/padraicb/status/595931787563499521

**Comment by Seldaek** [comment]
:+1: it'd be great to have this so we can try to enforce ssl on packagist and see what else breaks :)

**Comment by remicollet** [comment]
* RHEL-6 provides php 5.3.3 which should be maintained until 2020...
* RHEL-7 provides php 5.4.16 which should be maintained until 2024...
Most of the patches are security patches (and some bugfix)

I think it easier to apply all the patches (than to try to select the most useful ones)

Notice: RH also provides php 5.4.40, 5.5.21 and 5.6.7 ;)  (in RHSCL).

**Comment by GrahamCampbell** [comment]
We're open to PRs please. :)
