### ISSUE TITLE
Add phpdbg support

### ISSUE THREAD

**Issue by CHH** [php-build/php-build#164]
Add support for [phpdbg](https://github.com/krakjoe/phpdbg). I think this is so useful and free of side effects, that it could be built-in by default.

**Comment by GrahamCampbell** [comment]
This would be cool, especially for php 7.

**Comment by alariva** [comment]
@BanzaiMan Thanks, +1 here.

Is there any workaround available so far (for using the same build scripts for 5.6 and 7)? like running PHP 7 with XDebug, until this get's ready?

Thanks!

**Comment by Jean85** [comment]
+1 here too, this is a blocker for using it to collect code coverage on Travis, which would be a lot faster (and pretty awesome)

**Comment by GrahamCampbell** [comment]
I find that phpdbg isn't so useful for large projects, or even, just anything non-trivial, because of the limit it imposes on the number of files that can be loaded at once.

**Comment by Jean85** [comment]
Can't the limit be increased? Anyhow, I maintain facile-it/paraunit, which collects coverage in parallel per-test-class: that approach will reduce the number of loaded files per process, overcoming this issue.

**Comment by GrahamCampbell** [comment]
> Can't the limit be increased?

Maybe, but I guess it gets slower and slower, and slower, making xdebug faster for anything but small projects. Your approach of splitting things up like that probably would mitigate this issue for most use cases though.

Alright, I'm satisfied this is useful. I guess we'd accept a PR to add this. :)

**Comment by hnw** [comment]
I think this issue has been resolved by #413.

**Comment by GrahamCampbell** [comment]
👍
