### ISSUE TITLE
Handle installing of PHP's build-dependencies

### ISSUE THREAD

**Issue by CHH** [php-build/php-build#19]
Provide some scripts for APT and YUM to install all needed dependencies, so no more `configure => error => look up packages => configure => ...` is needed.

Place scripts for each distribution in a `contrib` directory, e.g. `contrib/ubuntu.sh` for setting up the build dependencies for Ubuntu.

**Comment by smola** [comment]
I think https://github.com/php-build/php-build/pull/635 can be considered a fix for this issue.
