### ISSUE TITLE
Transfer repository over to the "php-build" org

### ISSUE THREAD

**Issue by CHH** [php-build/php-build#245]
The purpose of this issue is to track the tasks necessary for moving this repo to the [php-build](https://github.com/php-build) org.

Why I think we should do this:

* Decouples the project more from my person, especially because I'm not really involved much.
* I can have my own private branches here if I choose to, released branches can be made public in the org's repo
* Allows to group the repos of plugins under a common org

Open Questions

- [x] Transfer or Fork the repo over to the org? -> Transfer

**Comment by rogeriopradoj** [comment]
Hi, @CHH and @loicfrering. Waking up the discussion, what we could do to continue with this process?

**Comment by CHH** [comment]
I guess I'll just do it. The only open question is, when to do it

**Comment by GrahamCampbell** [comment]
Now is as good as ever. :P

**Comment by rogeriopradoj** [comment]
@CHH , and I think we could invite @GrahamCampbell for getting more involved as well (perhaps even participate of the transfer process).

https://gist.github.com/paulmillr/2657075/ shows he is the "# 7" most active GitHub user, and lots of the contributions were to `php-build`!

**Comment by GrahamCampbell** [comment]
> shows he is the "# 7" most active GitHub user, and lots of the contributions were to php-build!

ooooooh - i had no idea!

**Comment by rogeriopradoj** [comment]
:smiley: congrats!

**Comment by CHH** [comment]
So no objections to adding @GrahamCampbell to the org and the repo?

**Comment by GrahamCampbell** [comment]
:+1: :P

**Comment by CHH** [comment]
(I wanted to post this first :smirk:, but you beat me :laughing:)

@GrahamCampbell I want to invite you to join the php-build org, to be a collaborator and a core team member if the other core team members have no objections. How do you feel about this? :smiley:

**Comment by GrahamCampbell** [comment]
> How do you feel about this?

That would be totally fine. :)

**Comment by CHH** [comment]
Regarding the transfer, the only reason I've been hesitant is, that I don't know how projects that depend on php-build are affected by the move to the org? Anyone opinions/experiences about this?

**Comment by GrahamCampbell** [comment]
> Anyone opinions/experiences about this?

Provided you never fork the repo back here, and leave CHH/php-build clear, github will actually redirect all traffic including git stuff over to the new repo.

**Comment by GrahamCampbell** [comment]
So cloning CHH/php-build will still work even after you have moved to repo to an org.

**Comment by GrahamCampbell** [comment]
https://help.github.com/articles/transferring-a-repository/

**Comment by CHH** [comment]
Thanks that clears things up quite a bit. I'll make the move ASAP.

**Comment by CHH** [comment]
Transferred: https://github.com/php-build/php-build

**Comment by CHH** [comment]
@rogeriopradoj @loicfrering any objections about adding @GrahamCampbell to the core team?

**Comment by GrahamCampbell** [comment]
Is https://github.com/CHH/php-build-plugin-phpunit getting moved too?

**Comment by CHH** [comment]
thanks for reminding me :)

**Comment by CHH** [comment]
done :)

**Comment by GrahamCampbell** [comment]
:ship:

**Comment by thaJeztah** [comment]
Great! And congratulations, @GrahamCampbell

**Comment by loicfrering** [comment]
Great, thanks @CHH and congratulations @GrahamCampbell you did an awesome work!

**Comment by rogeriopradoj** [comment]
No objection!!!
