### ISSUE TITLE
Problem installing php-build (mcrypt.h not found)

### ISSUE THREAD

**Issue by chrispadfield** [php-build/php-build#291]
I'm installing php-build on a clean ubuntu Ubuntu 14.04 x64 VM and following instructions here https://php-build.github.io/

Running php-build -i development 5.5.9 ~/local/php/5.5.9 I get:
> /-----------------------------------------
> configure: WARNING: bison versions supported for regeneration of the Zend/PHP parsers: 
> 2.4 2.4.1 2.4.2 2.4.3 2.5 2.5.1 2.6 2.6.1 2.6.2 2.6.3 2.6.4 2.6.5 2.7 (found: 3.0).
> configure: error: mcrypt.h not found. Please reinstall libmcrypt.
> /-----------------------------------------

Running

> sudo apt-get install php5-mcrypt
> sudo php5enmod mcrypt 

Has not helped.

Any suggestions?

**Comment by chrispadfield** [comment]
I fixed this (and another similar error) running

apt-get install libmcrypt-dev libreadline-dev

**Comment by GrahamCampbell** [comment]
Great you've got this fixed. Could you send a PR to our docs please?

**Comment by chrispadfield** [comment]
Done; hope ok. First PR for someone else's project :)

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by rogeriopradoj** [comment]
Hi, @chrispadfield , awesome!

There is https://github.com/rogeriopradoj/phpenv-common-deps-install where it suggest some common dependencies.

There is a list of some tools in the projects's wiki  that can be useful: https://github.com/php-build/php-build/wiki/phpenv%20tools

And again, congrats on your PR!
