### ISSUE TITLE
No libphp5.so built (due to patch failing to apply?)

### ISSUE THREAD

**Issue by ghost** [php-build/php-build#295]
Hello

I am trying to build PHP 5.5.27, and this succeeds, but when the build is finished, there is no libphp5.so in the libexec folder (in fact the folder is completely empty). The log contains the following (along with some GCC warnings, but no other errors):

```
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
```

This happens with the latest git master version. I think the patch, which sets the location for the library and the culprit, is located at [1].

Thanks in advance for any help you can offer

[1] https://github.com/php-build/php-build/blob/master/bin/php-build#L625

**Comment by webnard** [comment]
I'm getting the same issue with installing 5.4.43.

**Comment by hotoiledgoblinsack** [comment]
@webnard Even though this is still an issue, if you really want to use php-build, you may have more luck setting up php-fpm with sockets instead (you can find it in the `sbin` folder after PHP is built). After some tinkering I got it working by having each php-fpm listen to a different socket and configuring each vhost with the desired socket via SetHandler (this way I can have a separate PHP version per vhost).

**Comment by rogeriopradoj** [comment]
https://github.com/phpenv/phpenv/issues/57#issuecomment-155549311
