### ISSUE TITLE
No X-Debug being installed

### ISSUE THREAD

**Issue by bweston92** [php-build/php-build#311]
```
php-build -i development 5.6.13 $HOME/php
```

Then on the build php binary `php --version`

```
PHP 5.6.13 (cli) (built: Oct  9 2015 08:30:45)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

No X-Debug.

Any ideas?

**Comment by GrahamCampbell** [comment]
Are you sure it's enabled?

**Comment by GrahamCampbell** [comment]
That is, in your php config.

**Comment by bweston92** [comment]
I don't have PHP installed on the system at all, only by phpenv.

**Comment by GrahamCampbell** [comment]
Yes, but you still must have php config.

**Comment by bweston92** [comment]
Sorry for my lack of knowledge on phpbuild or building php at all, I followed; https://php-build.github.io/

**Comment by rogeriopradoj** [comment]
Hi, @bweston92, can I try to help you?

Firstly, confirm if your definition for 5.6.13 contains this line:
https://github.com/php-build/php-build/blob/master/share%2Fphp-build%2Fdefinitions%2F5.6.13#L3.

Secondly, take a look at your php config files (after installation), in order to ensure how xdebug is configured. In my case, for example (I've installed 5.6.14 now), I get the following:

```
$ php --ini

Configuration File (php.ini) Path: /Users/rogerio/.phpenv/versions/5.6.14/etc
Loaded Configuration File:         /Users/rogerio/.phpenv/versions/5.6.14/etc/php.ini
Scan for additional .ini files in: /Users/rogerio/.phpenv/versions/5.6.14/etc/conf.d
Additional .ini files parsed:      /Users/rogerio/.phpenv/versions/5.6.14/etc/conf.d/pyrus.ini,
/Users/rogerio/.phpenv/versions/5.6.14/etc/conf.d/xdebug.ini
```

So I took a look at xdebug.ini:
```
$ cat /Users/rogerio/.phpenv/versions/5.6.14/etc/conf.d/xdebug.ini

zend_extension="/Users/rogerio/.phpenv/versions/5.6.14/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so"
html_errors=on
```

Could you show to us what is showing in your configs?

P.S.: Take a look at https://github.com/rogeriopradoj/phpenv-installer and https://github.com/php-build/php-build/wiki/phpenv-tools. 

I think CHH/phpenv will help you to change between php-build php generate versions in future, alright?

**Comment by bweston92** [comment]
@rogeriopradoj thank you for taking the time to help. Unfortunately the "Loaded configuration file" is `(none)`

```
gitlab-runner@TORRENS:~$ php --ini
Configuration File (php.ini) Path: /usr/local/lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
gitlab-runner@TORRENS:~$ php --version
PHP 5.6.13 (cli) (built: Oct  7 2015 16:26:54)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
gitlab-runner@TORRENS:~$ which php
/home/gitlab-runner/.phpenv/shims/php
```

How-ever the definition does contain the `install_xdebug` statement.
``
[root@TORRENS]:~/php-build]# cat share/php-build/definitions/5.6.13
install_package "https://secure.php.net/distributions/php-5.6.13.tar.bz2"
install_pyrus
install_xdebug "2.3.3"
enable_builtin_opcache
```

**Comment by rogeriopradoj** [comment]
@bweston92: I've seen you're already using phpenv, right? What's the output when you run `phpenv versions`?

And what's the output when you run `whereis php` and `where php`?

I suspect that you have built the php with php-build/phpenv, but the php binary that's being called it the system version.

Please, send the outputs for us to confirm, ok?

See ya!

**Comment by bweston92** [comment]
Right I have 2 accounts `root` and `gitlab-runner`

`root`:
```
root@ci-bweston:~# whereis php
php:

root@ci-bweston:~# php --version
The program 'php' is currently not installed. You can install it by typing:
apt-get install php5-cli
```

`gitlab-runner`
```
gitlab-runner@ci-bweston:~$ whereis php
php:
gitlab-runner@ci-bweston:~$ php --version
PHP 5.6.13 (cli) (built: Oct  9 2015 08:30:45)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
gitlab-runner@ci-bweston:~$ which php
/home/gitlab-runner/.phpenv/shims/php
```

**Comment by rogeriopradoj** [comment]
Sorry, @bweston92 , I couldn't see what I was expecting. Please, post the outputs of these commands below (in each one of the accounts, right?):

```
$ whereis php

$ where php

$ which -a php

$ php -v

$ whereis phpenv

$ where phpenv

$ which -a phpenv

$ phpenv versions
```

**Comment by bweston92** [comment]
You're expecting a system PHP installed, there isn't which is why `root` doesn't have `php --version`.

```
root@ci-bweston:~# whereis php
php:
root@ci-bweston:~# where php
No command 'where' found, did you mean:
 Command 'gwhere' from package 'gwhere' (universe)
where: command not found
root@ci-bweston:~# which -a php
root@ci-bweston:~# php -v
The program 'php' is currently not installed. You can install it by typing:
apt-get install php5-cli
root@ci-bweston:~# whereis phpenv
phpenv:
root@ci-bweston:~# where phpenv
No command 'where' found, did you mean:
 Command 'gwhere' from package 'gwhere' (universe)
where: command not found
root@ci-bweston:~# which -a phpenv
root@ci-bweston:~# phpenv version
phpenv: command not found
```

```
gitlab-runner@ci-bweston:~$ whereis php
php:
gitlab-runner@ci-bweston:~$ where php
No command 'where' found, did you mean:
 Command 'gwhere' from package 'gwhere' (universe)
where: command not found
gitlab-runner@ci-bweston:~$ which -a php
/home/gitlab-runner/.phpenv/shims/php
gitlab-runner@ci-bweston:~$ php -v
PHP 5.6.13 (cli) (built: Oct  9 2015 08:30:45)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
gitlab-runner@ci-bweston:~$ whereis phpenv
phpenv:
gitlab-runner@ci-bweston:~$ where phpenv
No command 'where' found, did you mean:
 Command 'gwhere' from package 'gwhere' (universe)
where: command not found
gitlab-runner@ci-bweston:~$ which -a phpenv
/home/gitlab-runner/.phpenv/bin/phpenv
gitlab-runner@ci-bweston:~$ phpenv versions
phpenv v0.0.4-dev

* 5.6.13 (set by /home/gitlab-runner/.phpenv/version)
  7.0.0RC4

```

**Comment by rogeriopradoj** [comment]
Which phpenv have you installed? https://github.com/CHH/phpenv/ or https://github.com/phpenv/phpenv/

**Comment by bweston92** [comment]
CHH/phpenv as I seen on Travis CI.

**Comment by rogeriopradoj** [comment]
Oh my gosh, I don't know how to help you! Do you know https://asciinema.org/?

Would be greate if you could record your terminal screen while installing, since the beginning, in order to us provide you more support, ok?

Do you mind to make that? You'll probably have to uninstall all the things first...

See ya!

**Comment by bweston92** [comment]
I will have a go later.

**Comment by rogeriopradoj** [comment]
:+1:

**Comment by rogeriopradoj** [comment]
Hi, @bweston92 , closing right now while you make the new tests, ok?

Don't hesitate to reopen if the problem stills.

See ya!
