### ISSUE TITLE
pear.php.net certificate issue prevents compilation (no recent nightly builds on Travis CI)

### ISSUE THREAD

**Issue by BanzaiMan** [php-build/php-build#344]
PHP nightly builds have been failing the last 2 days. First, via connection timeout to pear.php.net, then now with certificate issue with the same host.

https://travis-ci.org/travis-ci/php-src-builder/jobs/94094279#L241-L247

```
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.
--2015-12-01 05:04:39--  https://pear.php.net/install-pear-nozlib.phar
Resolving pear.php.net (pear.php.net)... 5.35.241.22
Connecting to pear.php.net (pear.php.net)|5.35.241.22|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name `pear.php.net'.
To connect to pear.php.net insecurely, use `--no-check-certificate'.
```

Besides some custom configuration, the basic command we run is:

```
php-build -i development "${VERSION}" "${INSTALL_DEST}/${VERSION}"
```

(https://github.com/travis-ci/php-src-builder/blob/b51704810069121730270bdd9f79b5617d6fb7f8/bin/compile#L19)

**Comment by BanzaiMan** [comment]
https://twitter.com/official_php/status/671424892613427200

> pear.php.net update: still being worked on; no ETA on full restoration at present. Root cause of outage is a hardware failure.

I guess we'll wait and see.

**Comment by BanzaiMan** [comment]
The intermediate server is back up, so it is back to the certificate issue.

**Comment by BanzaiMan** [comment]
![screenshot_12_2_15__12_34_pm](https://cloud.githubusercontent.com/assets/25666/11538676/00a17824-98f1-11e5-82f0-6b39ac2bee1c.png)

**Comment by GrahamCampbell** [comment]
Ping @php-build/owners. Maybe we should jusr rip it out? :trollface:

**Comment by henriquemoody** [comment]
:+1: rip this thing out

**Comment by rogeriopradoj** [comment]
:+1:
