### ISSUE TITLE
Remove `--with-mysql` from default_configure_options

### ISSUE THREAD

**Issue by rogeriopradoj** [php-build/php-build#348]
https://github.com/php-build/php-build/blob/master/share/php-build/default_configure_options#L24 still has `--with-mysql`, which is generating a warning on compilations (I got this right know with PHP 7.0.0):

```
configure: WARNING: unrecognized options: `--with-mysql`
```

As we know that `ext-mysql` was removed since PHP 7+, and for so long time `ext-mysql` is deprecated  I think we should drop it, and let just `--with-mysqli`:

| --- | ext/mysqli | PDO_MySQL | ext/mysql |
| --- | --- | --- | --- |
| PHP version introduced | 5.0 | 5.1 | 2.0 |
| Included with PHP 5.x | Yes | Yes | Yes |
| Included with PHP 7.x | Yes | Yes | No |
| Development status | Active | Active | Maintenance only in 5.x; removed in 7.x |
| Lifecycle | Active | Active | Deprecated in 5.x; removed in 7.x |
| Recommended for new projects | Yes | Yes | No |
| OOP Interface | Yes | Yes | No |
| Procedural Interface | Yes | No | Yes |
| API supports non-blocking, asynchronous queries with mysqlnd | Yes | No | No |
| Persistent Connections | Yes | Yes | Yes |
| API supports Charsets | Yes | Yes | Yes |
| API supports server-side Prepared Statements | Yes | Yes | No |
| API supports client-side Prepared Statements | No | Yes | No |
| API supports Stored Procedures | Yes | Yes | No |
| API supports Multiple Statements | Yes | Most | No |
| API supports Transactions | Yes | Yes | No |
| Transactions can be controlled with SQL | Yes | Yes | Yes |
| Supports all MySQL 5.1+ functionality | Yes | Most | No |

> Table source: http://dev.mysql.com/doc/apis-php/en/apis-php-mysqlinfo.api.choosing.html

**Comment by Ryckes** [comment]
I am installing PHP7 right now (latest version from http://php.net/downloads.php) and in the INSTALL file, the instructions for Apache2 still include --with-mysql. I am getting the same warning when I run configure.

**Comment by ikari7789** [comment]
Would it be better to add ```configure_option "--with-mysql"``` to definitions that still supported ```--with-mysql```?

**Comment by rogeriopradoj** [comment]
> I am installing PHP7 right now (latest version from http://php.net/downloads.php) and in the INSTALL file, the instructions for Apache2 still include --with-mysql. I am getting the same warning when I run configure.
> https://github.com/php-build/php-build/issues/348#issuecomment-164234641

Interesting, @Ryckes. Now I don't know the best strategy...

**Comment by rogeriopradoj** [comment]
> Would it be better to add configure_option "--with-mysql" to definitions that still supported --with-mysql?
> https://github.com/php-build/php-build/issues/348#issuecomment-164326484

@ikari7789 I think it's a good way to go!

**Comment by GlenKPeterson** [comment]
With php-7.0.5 on Ubuntu 15.10 I was following the instructions here:
http://php.net/manual/en/install.unix.nginx.php

Step 3 says:
```
cd ../php-x.x.x
./configure --enable-fpm --with-mysql
```

But I got:
```
configure: WARNING: unrecognized options: --with-mysql
```

I changed `--with-mysql` to `--with-mysqli` and it seemed to work.  If that's a good fix, it would have been more helpful for the message to read:
```
the --with-mysql option has been replaced with --with-mysqli
```

**Comment by rogeriopradoj** [comment]
Hello, @GlenKPeterson . I think the message you pointed is generated by php compilation process itself, and not by php-build. So unfortunatelly I don't know if we could handle the message as you suggested

**Comment by wedojava** [comment]
The 2 solution to this error that I get,but which one is the better than?

    - __Solution1:__　`--with-pdo-mysql` instead of `--with-mysql`
    - __Solution2:__　`--with-mysqli` instead of `--with-mysql`

**Comment by threewing** [comment]
using "php-7.0.12", I hit the same problem when I do "sudo ./configure --with-mysql", reading:
configure: WARNING: unrecognized options: --with-mysql

**Comment by Forecaster** [comment]
Got above warning as well since using --with-mysql from the nginx install instructions from php.net, found this issue, now using --with-mysqli instead
(Ubuntu-server-16.04)
