### ISSUE TITLE
Remove unsupported-versions from run-tests.sh.STABLE_DEFINITIONS

### ISSUE THREAD

**Issue by rogeriopradoj** [php-build/php-build#349]
The idea is removing unstable definitions from https://github.com/php-build/php-build/blob/master/run-tests.sh#L4 (because of the name of that variable, `STABLE_DEFINITIONS`), but keep the builds on Travis-CI.

> http://php.net/supported-versions.php
> http://php.net/eol.php

**Comment by GrahamCampbell** [comment]
:-1: Still useful to check they still work though?

**Comment by rogeriopradoj** [comment]
Hi, @GrahamCampbell , in fact they are not useful for that. Nowadays checking is being done in travis passing each of the php versions we want to verify.

We can see that it's common not even update this file https://github.com/php-build/php-build/blob/master/run-tests.sh when Pull Request updating the definitions are done.

As it don't have impact in your main ecosystem and flow, I'll let the issue open for new contributors only (trying to advocate https://yourfirstpr.github.io/ and  [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](http://makeapullrequest.com))!

**Comment by 2346725982** [comment]
Hi @rogeriopradoj , first timer here. I would like to try to help. But I'm quite not sure what to do really..

Should I just remove the unsupported version number from the variable? Is it just like a one line change?..

Hope to get your reply. Thanks!

**Comment by rogeriopradoj** [comment]
Hi, @2346725982 , welcome!

> Should I just remove the unsupported version number from the variable? Is it just like a one line change?..

Yeah, that's it! Use http://php.net/supported-versions.php as your guide, ok?

See ya!

**Comment by rogeriopradoj** [comment]
@2346725982 if needed, you can use [this GitHub guide](https://guides.github.com/activities/contributing-to-open-source/) for managing your Pull Request, and don't hesitate asking for help, ok?

See ya!

**Comment by 2346725982** [comment]
Hi @rogeriopradoj , I just made my fork and the pull request. Not whether I did it right or not though.. Hope you can take a look. Thanks!

**Comment by GrahamCampbell** [comment]
What if people want to use this repo to get old versions of php running, purely for academic purposes. I don't think we should just kill off the old versions, even though I wouldn't want to see anyone using older than php 5.6 in production.
