### ISSUE TITLE
PHP 5.2.17 seems to be inconsistent

### ISSUE THREAD

**Issue by debo** [php-build/php-build#351]
Just a curiosity, I know that I'm definitely doing something wrong and unnecessary because this version is well beyond being outdated and unsupported but I was trying to build php 5.2.17 on OSX 10.11 and I kept getting the following error:
```bash
warning: assigning to 'char *' from 'xmlChar *' (aka 'unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
```
I remember having the very same issue on another machine like this and I solved doing a:
```bash
~ brew link libxml2 --force
```
However that solution didn't work this time. Adter lots of googling I found [this link](http://qiita.com/y_arakawa/items/8c3b6f2bf7f3e75fd01f) that suggest to patch the sources. I was wondering why the two different behaviours and whether the patch should be part of php-build?

**Comment by debo** [comment]
Ok, pebkac, I'm going to close the issue, I was running an old version of php-build on that machine. It looks like the patch was re-introduced few weeks ago.

**Comment by rogeriopradoj** [comment]
:+1:
