### ISSUE TITLE
php version 5.2.17 isn't building on ubuntu 14.04

### ISSUE THREAD

**Issue by keshavkaul** [php-build/php-build#373]
Here is the Error Output :

```
-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
configure: warning: bison versions supported for regeneration of the Zend/PHP parsers: 1.28 1.35 1.75 1.875 2.0 2.1 2.2 2.3 2.4 2.4.1 (found: 3.0.2).
configure: warning: flex versions supported for regeneration of the Zend/PHP parsers: 2.5.4  (found: 2.5.35)
configure: error: libjpeg.(a|so) not found.
-----------------------------------------
```
i have found the required file at `/usr/lib/x86_64-linux-gnu/libjpeg.(a | so)`
Any suggestion on why this error is generated?

**Comment by keshavkaul** [comment]
@rogeriopradoj Would appreciate any help. Thanks

**Comment by GrahamCampbell** [comment]
You need to downgrade some of your installed libraries to get php 5.2 to work.

**Comment by GrahamCampbell** [comment]
PHP 5.2 is old enough, maybe you'd be best off just installing an older ubuntu release, that ships with the old libraries? Maybe 10.04 or something?

**Comment by rogeriopradoj** [comment]
hello, guys!

@keshavkaul , as @GrahamCampbell , the point is to downgrade some of the libraries.

In https://github.com/rogeriopradoj/phpenv-common-deps-install/ I tried to put the most generic deps, but they are not tied with specific php versions but with operation system.

What do you think to work on make a new https://github.com/rogeriopradoj/phpenv-common-deps-install/blob/master/bin/phpenv-common-deps-install-ubuntu-14-04 for example as phpenv-common-deps-install-ubuntu-14-04-php5.2.17 ? Let's do it?

**Comment by smartymoon** [comment]
php-build will check this lib in /usr/lib64 , so you can  do this: ln  -s /usr/lib64  your lib

**Comment by Potherca** [comment]
I'm getting a similar error trying to install PHP 5.6.21 on Ubuntu 16.04. Am I correct in thinking that to fix this, I should open a ticket/PR on (phpenv-common-deps-install)[https://github.com/rogeriopradoj/phpenv-common-deps-install], adding support there?

**Comment by rogeriopradoj** [comment]
> I'm getting a similar error trying to install PHP 5.6.21 on Ubuntu 16.04. Am I correct in thinking that to fix this, I should open a ticket/PR on phpenv-common-deps-install, adding support there?

@Potherca: I think so. By the side of php-build itself there's nothing to do. I'll for you there

**Comment by Potherca** [comment]
As I did not have any time to invest in this, I switched to using [PhpBrew](https://github.com/phpbrew/phpbrew) instead.
