### ISSUE TITLE
What is the correct path for libphp.so?

### ISSUE THREAD

**Issue by kimh** [php-build/php-build#375]
Hi, I built PHP 7.0.4 by using php-build and I want to get `libphp7.so` file to be created so I've added `with_apxs2` to the definition file.

One thing I'm wondering is that `lihbphp7.so` is created under `${PREFIX}/usr/lib/apache2/modules/libphp7.so` but I see some people say it has to be created under `${PREFIX}/libexec/apache2/libphp7.so` or even `${PREFIX}/libexec/libphp7.so`.

I read the code and the file is created whatever `apxs2 -q LIBEXECDIR` returns [here](https://github.com/php-build/php-build/blob/master/bin/php-build#L578), so I think the behavior is correct. However, creating the php module under the subdirectory `usr/lib/apache2/modules` still looks strange to me. Is this something people agree with?

**Comment by ikari7789** [comment]
Well it would depend on your Apache setup. In my case we're using a custom compiled Apache under /usr/local, so for us it's /usr/local/apache/libexec/libphp*.so. Technically I don't see a problem moving it after compilation. I personally like that it mirrors the apache install location, but I can also see that becoming a problem if you change your Apache's install settings in some way (then it doesn't match up anymore).

Perhaps ```${PREFIX}/libexec/apache2/libphp*.so``` would be a better "standard" location?

**Comment by kimh** [comment]
> Well it would depend on your Apache setup

It's good to know that it depends on setups, so my answer is now answered. Thanks for your response!
