### ISSUE TITLE
AUR packages

### ISSUE THREAD

**Issue by sagikazarmark** [php-build/php-build#381]
Hey there

FYI I created AUR packages for php-build:

https://aur.archlinux.org/packages/?O=0&SeB=nd&K=php-build&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by rogeriopradoj** [comment]
Nice, @sagikazarmark , thanks for sharing.

In case someone is interested in the future, they can search here in [project issues](https://github.com/php-build/php-build/issues).

**Comment by sagikazarmark** [comment]
@rogeriopradoj when do you prepare releasing the next version. The currently tagged version does not work installed into the global prefix.
