### ISSUE TITLE
Enable bzip2 by default

### ISSUE THREAD

**Issue by mbrodala** [php-build/php-build#392]
In addition to the support for Gzip thanks to zlib Bzip2 should also be enabled by default IMO.

This would require [one additional build dependency](http://php.net/manual/en/bzip2.requirements.php) AFAIS.

**Comment by hnw** [comment]
Now bz2 extensiton is enabled by default (see #431 ) . I think this can be closed now.

**Comment by mbrodala** [comment]
Thanks a lot. :-)
