### ISSUE TITLE
Can we get a new release tag for Homebrew?

### ISSUE THREAD

**Issue by joshuap** [php-build/php-build#407]
I just installed `php-build` via Homebrew (actually, Linuxbrew!) but noticed that the [Formula](https://github.com/Homebrew/homebrew-php/blob/master/Formula/php-build.rb) is linked against a very old 0.10.0 release from 2013, which seems to be the last release tag. Can you guys tag a new release so we can update the Formula?

**Comment by GrahamCampbell** [comment]
Once https://github.com/php-build/php-build/issues/276 is addressed, yes. :)
