### ISSUE TITLE
Installer broken on FreeBSD

### ISSUE THREAD

**Issue by petehayes102** [php-build/php-build#418]
When I run php-build on FreeBSD I get this error:
>env: .phpenv/plugins/php-build/bin/../share/php-build/before-install.d/*: No such file or directory

There's a line in `bin/php-build` that appears in `trigger_(before|after)_install()` that causes this unexpected behaviour:

```
for trigger in "$triggers_dir"*; do
```

Changing it to this works fine:

```
for trigger in "$triggers"; do
```

**Comment by hnw** [comment]
I think you have no `share/php-build/before-install.d/` directory. If php-build is correctly installed , there are `share/php-build/before-install.d/` directory and `share/php-build/before-install.d/.empty` file.

I recommend you to re-install php-build ( and phpenv ).
