### ISSUE TITLE
Failing MAC CI Builds

### ISSUE THREAD

**Issue by GrahamCampbell** [php-build/php-build#428]
Travis currently failing for our MAC builds.

**Comment by hnw** [comment]
The libevent 2.1.8 was released on 22 Jan, and it's incompatible with libevent 2.0.x. PHP 5.3.3 works only with libevent 2.0.x, so now the build is failed.

PHP 5.3.3 seems experimental version (it's only version which requires libevent), so I think this version will no longer be supported.
