### ISSUE TITLE
Add ability to install latest major/minor version

### ISSUE THREAD

**Issue by ikari7789** [php-build/php-build#460]
It would be useful to be able to provide just the major version of PHP (e.g. 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, etc) and have it install the latest definition available for that major version. I'm not sure if this would best be accomplished through code or by just simply creating a new definition.

**Comment by GrahamCampbell** [comment]
So, you mean the latest minor version I think?

**Comment by GrahamCampbell** [comment]
I'd be tempted to just add another definition file for each minor version to implement this. 👍

**Comment by hnw** [comment]
I think simply adding new definition like `7.1` is not a good idea. Because we don't know which version of 7.1.x is installed under the name 7.1.

It's better that `php-build 7.1` build the latest minor version with correct name (like 7.1.8).

**Comment by ikari7789** [comment]
I'm in agreement with @hnw. Hence why I made this an issue rather than a simple PR to the definitions. Also, inevitably, someone will forget to update the definitions when adding new releases.

I think ideally, this should have the following functionality:
- If definition matches just major/minor version (i.e. `php-build X` or `php-build X.Y`)
  - Determine the latest definition file (`X.Y.Z`)
  - Install as usual
- Create symlink to (`X` and `X.Y`)

As for creating a symlink, to avoid implementing any kind of breaking changes, perhaps it could be done only when specifying a specific switch, like `--create-symlinks`.

**Comment by madumlao** [comment]
Just for reference, the opposite of this functionality - alias "7.2" to the latest 7.2.x installed - is provided by the `*env-aliases` family of `*env` projects, with [phpenv-aliases](https://github.com/madumlao/phpenv-aliases) being the php equivalent.

I know it doesnt actually answer the issue, but another phpenv plugin could be written to do this job. That way php-build only needs to bother with exact version names, and its easy to port to other `*env` scripts.

**Comment by madumlao** [comment]
On checking, i could actually integrate it into phpenv-aliases itself, if you're not planning for it on php-build.

**Comment by ikari7789** [comment]
@madumlao That would probably be great if you could do that! I just noticed your plugin (must've missed the update notification for this thread).

**Comment by allanlaal** [comment]
linked: #714

**Comment by madumlao** [comment]
Funny thing, it's been a couple of years but now this feature can be revisited. When this feature was first requested, one of the blockers was that the original phpenv repo was out of our control and would break if some features were added to php-build that allow hooks. Things have changed since then and with interest revived I may be able to add this feature into phpenv-aliases in earnest, so that php-build only needs to deal with exact point versions.

Unless of course, you want to implement this in php-build yourself.

**Comment by allanlaal** [comment]
@madumlao can you enable `issues ` on the phpenv-aliases repo?
