### ISSUE TITLE
Wishlist: Ability to select mirror

### ISSUE THREAD

**Issue by minbaby** [php-build/php-build#476]
#81 

I had found this `Wishlist: Ability to select mirror`. I think it's usefull for somebody like me. 

I know all the links contained in definitions are working fine, but too slow. 

I hope to use the environment variable to configure the mirror， like this

```
## for brew bottle
epport HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
```

**Comment by smola** [comment]
PHP mirrors were retired in 2019 ([see the announcement](https://derickrethans.nl/php-mirrors.html)) so this feature is kind of obsolete. It would still be useful if there are users with their own private mirror, but it seems nobody asked for that so far.

**Comment by GrahamCampbell** [comment]
If anyone really needs this, they can implement it themselves and send a PR. I think that's a fair stance to take.
