### ISSUE TITLE
Add PHP 7.3-alpha

### ISSUE THREAD

**Issue by trasher** [php-build/php-build#509]
Hi,

Would it be possible to add PHP 7.3 (which reached alpha2 stage a few days ago)?

Thanks you very much!

**Comment by trasher** [comment]
Asked on travis issue already: https://github.com/travis-ci/travis-ci/issues/9717 (but I guess it must be added here so Travis can use it).

**Comment by TysonAndre** [comment]
https://github.com/php-build/php-build/pull/515 added images for PHP 7.3alpha4.

I'm not familiar with this project; Is anything else needed for this ticket?

- If travis is waiting for the betas, 7.3.0beta1 is out.

**Comment by GrahamCampbell** [comment]
New PHP 7.1, 7.2, and 7.3 releases are scheduled for Thursday. phpbuild will be upgraded then. In the meanwhile, all the latest releases as of three weeks ago are currently available on phpbuild.
