### ISSUE TITLE
"rbenv: no such command `install'" when trying to `phpenv install`

### ISSUE THREAD

**Issue by mhart** [php-build/php-build#516]
Steps to reproduce:
```
$ curl -sSL http://git.io/phpenv-installer | bash
$ export PATH=~/.phpenv/bin:$PATH
$ eval "$(phpenv init -)"
$ phpenv install 7.1.20
rbenv: no such command `install'
```

Has only started happening since #510

**Comment by madumlao** [comment]
I can look into it this weekend. disclosure: Im the maintainer of madumlao/phpenv which has diverged a bit from CHH/phpenv used by phpenv-installer (and is closer to upstream rbenv). The latter might need to be updated.

**Comment by mhart** [comment]
Yeah, this is still the first recommended way of installing as per the README, so I imagine a bunch of ppl will run into it: https://github.com/php-build/php-build#as-phpenv-plugin

**Comment by madumlao** [comment]
I see. We should do 2 things then:
1) symlink the rbenv executables

2) update phpenv-installer to use the active phpenv version (mine madumlao/phpenv, because phpenv/phpenv also died)

I can put in some work on both in a bit

**Comment by madumlao** [comment]
3 things - update the readme not to use CHH/phpenv

**Comment by robertpustulka** [comment]
I can confirm this has also happened on my end.

The php-build is installed as phpenv plugin manually.

**Comment by GrahamCampbell** [comment]
Fixed. :)
