### ISSUE TITLE
Disable build of version 5.2.17 to get newer versions on upstream projects

### ISSUE THREAD

**Issue by ottlinger** [php-build/php-build#562]
There seems to be a problem with builds of v5.2.17 on Mac - thus disable it to get other newer versions in upstream services like Travis.

**Comment by ottlinger** [comment]
https://github.com/php-build/php-build/pull/563 was rejected, filed a new bug instead https://github.com/php-build/php-build/issues/565

**Comment by GrahamCampbell** [comment]
Fixed now.

**Comment by henriquemoody** [comment]
Awesome work, @GrahamCampbell!
