### ISSUE TITLE
[help wanted] PHP v5.2.17 build takes too long 

### ISSUE THREAD

**Issue by ottlinger** [php-build/php-build#565]
At the moment 5.2.17-builds take too long and run into timeouts on Travis resulting in upstream project being unable to fetch newer PHP versions.

Temporarily disabling this version (https://github.com/php-build/php-build/pull/563) was not accepted, so help & ideas are needed to fix the build.

Thanks for any comments .....

**Comment by mizunashi-mana** [comment]
I suggest building `5.2.x` without mysql extension on travis.

**Comment by ottlinger** [comment]
@GrahamCampbell as the build is still red, no upstream availability for newer PHP versions.

**Comment by GrahamCampbell** [comment]
I was aware. This is now fixed.

**Comment by ottlinger** [comment]
@GrahamCampbell thanks for the update and changes - all new(er) versions are available via Travis - kewl!
