### ISSUE TITLE
`--with-kerberos` as default build flag

### ISSUE THREAD

**Issue by fabiang** [php-build/php-build#575]
Hello,

is there any reason that `--with-kerberos` is a default build flag? It seems that some extensions now check for the flag in current master (7.4). I don't see why, because I guess not much people use Kerberos together with PHP.

For those who having problems compiling PHP 7.4 master, just make sure you have `libkrb5-dev` (Fedora/CentOS) installed or you'll get:

    configure: error: Package requirements (krb5-gssapi krb5) were not met:

Thanks!

**Comment by GrahamCampbell** [comment]
Thanks for the heads up. Maybe we should remove it from the defaults? I don't know how widely used the extension is. Ping @php-build/collaborators. :)

**Comment by edubacco** [comment]
subscribe

**Comment by Dziamid-Harbatsevich** [comment]
Ubuntu 20.04 LTS php-8.0.0beta1
I needed to install "libkrb5-dev" to proceed php building.
libkrb5-dev  (headers and development libraries for MIT Kerberos)
List of other krb5 packages: https://launchpad.net/ubuntu/focal/+source/krb5

**Comment by GrahamCampbell** [comment]
I've removed it from the defaults now. I'm sure we'll find out via a new issue if that is a problem for anyone. :)
