### ISSUE TITLE
PHP 7.3 Linux Travis Failures

### ISSUE THREAD

**Issue by GrahamCampbell** [php-build/php-build#579]
Builds are failing to to libzip not being available (or being too old).

**Comment by ottlinger** [comment]
Is that the reason for build failures on Travis?
https://travis-ci.org/travis-ci/php-src-builder/jobs/543333216
and newer versions not being available at the moment.

I just stumbled upon the missing versions. Thanks.

**Comment by ottlinger** [comment]
Firstly I thought it has to do with the used/underlying ubuntu version, but the build failures happen under 14.04 and 16.04 Ubuntu.

**Comment by GrahamCampbell** [comment]
Oh, I already fixed this a few days ago. The travis build should already be green again.

**Comment by ottlinger** [comment]
I thought so to, but as above link shows the build is still red and newer versions are unavailable.

**Comment by GrahamCampbell** [comment]
Our builds are passing: https://travis-ci.org/php-build/php-build/builds/540963835. They will need to make the same change in their repo that we did, or upgrade libzip to a version that is not shiped via apt-get.

**Comment by ottlinger** [comment]
@GrahamCampbell can you change the title of the issue to "Travis" so that others do not open new issues for the same cause - thanks.

**Comment by GrahamCampbell** [comment]
I'm going to close this since it doesn't relate to this package, actually. Travis' other repo not working is because PHP itself has changed the minimum version of libzip, which is unrelated to this repo.

**Comment by GrahamCampbell** [comment]
Looking at that link you sent, their builds are failing due a network issue or GitHub being down when their build ran.

**Comment by ottlinger** [comment]
@GrahamCampbell I interpret the build failures that Travis is unable to make the newer versions work with their Ubuntu images ....

@BanzaiMan is the build failure at https://travis-ci.org/ottlinger/hornherzogen not related to the new(er) PHP versions? Thanks.

**Comment by GrahamCampbell** [comment]
> Is the build failure at https://travis-ci.org/ottlinger/hornherzogen not related to the new(er) PHP versions? Thanks.

It looks like it is due to that, but not because of this repo.

**Comment by GrahamCampbell** [comment]
> I interpret the build failures that Travis is unable to make the newer versions work with their Ubuntu images ....

Yes, that is correct, but the issue is not with this repo. :)
