### ISSUE TITLE
[Suggestion] Release major version

### ISSUE THREAD

**Issue by oleg-andreyev** [php-build/php-build#619]
I'd like to propose to release a major version of `php-build` to remove old PHP 5.x support.

**Comment by GrahamCampbell** [comment]
We certainly need to keep PHP 5 I'm afraid. This package is used by travis ci, for example.

**Comment by GrahamCampbell** [comment]
PHP 5 will probably still be in this code base in 10 years too. One of the goals of this package is to allow anyone to compile almost any version of PHP, so it wouldn't make sense to remove old versions.
