### ISSUE TITLE
No package 'oniguruma' found

### ISSUE THREAD

**Issue by mouday** [php-build/php-build#709]
$ phpenv install 8.1.2
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 8.1.2 into ~/.phpenv/versions/8.1.2
[Skipping]: Already downloaded and extracted https://www.php.net/distributions/php-8.1.2.tar.bz2
[Preparing]: /var/tmp/php-build/source/8.1.2

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
configure: error: Package requirements (oniguruma) were not met:

No package 'oniguruma' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
-----------------------------------------

The full Log is available at '/tmp/php-build.8.1.2.20220224220325.log'.
[Warn]: Aborting build.

**Comment by hakimzulkufli** [comment]
@mouday You need to install `libonig-dev`.
