### ISSUE TITLE
5.3.15, 5.3.16 is not building on OSX 10.8.1

### ISSUE THREAD

**Issue by CHH** [php-build/php-build#79]
I get strange `ld` errors when attempting to compile 5.3.15 or 5.3.16 on OSX 10.8.1

```
ld: library not found for -lltdl
```

**Comment by mikepc** [comment]
I'm receiving this error and yet brew tells me I already have it installed?

**Comment by rogeriopradoj** [comment]
Hi, @mikepc , please open a new issue if the problem still happening for you, ok?
