### ISSUE TITLE
Wishlist: Ability to select mirror

### ISSUE THREAD

**Issue by Mezzle** [php-build/php-build#81]
As www.php.net's mirror is currently unavailable, it'd be nice to be able to select a mirror to use when downloading php distributions.

This would need to either substitute out www.php.net in the definitions, or replace them with variables.

**Comment by Mezzle** [comment]
Was this resolved?

**Comment by rogeriopradoj** [comment]
Hi, @Mezzle , how are you?

I think nowadays all the links contained in definitions are working fine.

That's the reason the issue is getting closed (right @GrahamCampbell? ).

Do you have any issues yet? Tell us more, ok?

**Comment by Mezzle** [comment]
Well, it'd be nice to be able to select a (more local, or internal to network) mirror...
